/*
Exercise 1.2 (Display five messages): 

Write a program that displays "Welcome to Java" five times.
Don't use "println" five times!

@Riyan Rattan
*/


package exercise01_02;

public class Exercise01_02 {
    public static void main(String[] args) {
        
         
        for (int i = 0; i < 5; i++) {
            System.out.println("Welcome to Java"); 
        }       
      }
    
    }
